### ISSUE TITLE
Unable to install 0.5.8

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#111]
Hello,

Pip error message

> C:\Users\saubert>pip install --upgrade --force-reinstall amphi-etl
Collecting amphi-etl
  Using cached amphi_etl-0.5.80.tar.gz (88 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\saubert\AppData\Local\Temp\pip-build-env-f3c4ysdc\overlay\Lib\site-packages\hatchling\build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\saubert\AppData\Local\Temp\pip-build-env-f3c4ysdc\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 90, in build
          self.metadata.validate_fields()
        File "C:\Users\saubert\AppData\Local\Temp\pip-build-env-f3c4ysdc\overlay\Lib\site-packages\hatchling\metadata\core.py", line 265, in validate_fields
          _ = self.version
              ^^^^^^^^^^^^
        File "C:\Users\saubert\AppData\Local\Temp\pip-build-env-f3c4ysdc\overlay\Lib\site-packages\hatchling\metadata\core.py", line 149, in version
          self._version = self._get_version()
                          ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\saubert\AppData\Local\Temp\pip-build-env-f3c4ysdc\overlay\Lib\site-packages\hatchling\metadata\core.py", line 244, in _get_version
          core_metadata = self.core
                          ^^^^^^^^^
        File "C:\Users\saubert\AppData\Local\Temp\pip-build-env-f3c4ysdc\overlay\Lib\site-packages\hatchling\metadata\core.py", line 196, in core
          metadata_hook.update(self.core_raw_metadata)
        File "C:\Users\saubert\AppData\Local\Temp\pip-build-env-f3c4ysdc\overlay\Lib\site-packages\hatch_nodejs_version\metadata_source.py", line 173, in update
          package = self.load_package_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\saubert\AppData\Local\Temp\pip-build-env-f3c4ysdc\overlay\Lib\site-packages\hatch_nodejs_version\metadata_source.py", line 125, in load_package_data
          raise OSError(f"file does not exist: {self.path}")
      OSError: file does not exist: package.json
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Best regards,

Simon

**Comment by tgourdel** [comment]
In all logic, it should be fixed, if there is an issue try:
`pip install --upgrade --force-reinstall amphi-etl jupyterlab-amphi`
Reopen if you have any issues :)
