### ISSUE TITLE
Unable to start amphi on last version

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#68]
Hello,

I just installed the last release. No issue during installation but unable to start amphi

`C:\Users\saubert>amphi start
Received command: start
Workspace directory: .
Port: 8888
IP: localhost
Python executable: C:\Users\saubert\AppData\Local\Programs\Python\Python312\python.exe
Environment PATH: C:\Program Files\Eclipse Adoptium\jdk-21.0.1.12-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.8.7-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\saubert\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\saubert\AppData\Local\Programs\Python\Python312\;C:\Users\saubert\AppData\Local\Microsoft\WindowsApps;;C:\Users\saubert\AppData\Local\Programs\Microsoft VS Code\bin
Running JupyterLab command: C:\Users\saubert\AppData\Local\Programs\Python\Python312\python.exe -m jupyter lab --notebook-dir=. --port=8888 --ip=localhost, --ContentManager.allow_hidden=true
[I 2024-08-01 11:02:29.323 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-08-01 11:02:29.333 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2024-08-01 11:02:29.339 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-08-01 11:02:29.348 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-08-01 11:02:29.348 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2024-08-01 11:02:29.349 ServerApp] nbdime | extension was successfully linked.
[W 2024-08-01 11:02:29.359 ServerApp] notebook_shim | error linking extension: [Errno 11001] getaddrinfo failed
    Traceback (most recent call last):
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\traitlets.py", line 632, in get
        value = obj._trait_values[self.name]
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
    KeyError: 'allow_remote_access'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\serverapp.py", line 1367, in _default_allow_remote
        addr = ipaddress.ip_address(self.ip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\ipaddress.py", line 54, in ip_address
        raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
    ValueError: 'localhost, --ContentManager.allow_hidden=true' does not appear to be an IPv4 or IPv6 address

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\extension\manager.py", line 346, in link_extension
        extension.link_all_points(self.serverapp)
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\extension\manager.py", line 228, in link_all_points
        self.link_point(point_name, serverapp)
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\extension\manager.py", line 218, in link_point
        point.link(serverapp)
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\extension\manager.py", line 140, in link
        linker(serverapp)
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\notebook_shim\nbserver.py", line 109, in _link_jupyter_server_extension
        members = diff_members(serverapp, nbapp)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\notebook_shim\nbserver.py", line 62, in diff_members
        m1 = public_members(obj1)
             ^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\notebook_shim\nbserver.py", line 56, in public_members
        members = inspect.getmembers(obj)
                  ^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 607, in getmembers
        return _getmembers(object, predicate, getattr)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 585, in _getmembers
        value = getter(object, key)
                ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\traitlets.py", line 687, in __get__
        return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
                         ^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\traitlets.py", line 635, in get
        default = obj.trait_defaults(self.name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\traitlets.py", line 1897, in trait_defaults
        return t.cast(Sentinel, self._get_trait_default_generator(names[0])(self))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\traitlets.py", line 1241, in __call__
        return self.func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\serverapp.py", line 1370, in _default_allow_remote
        for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 963, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    socket.gaierror: [Errno 11001] getaddrinfo failed
Traceback (most recent call last):
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\traitlets.py", line 632, in get
    value = obj._trait_values[self.name]
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\serverapp.py", line 1367, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'localhost, --ContentManager.allow_hidden=true' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Scripts\jupyter-lab.EXE\__main__.py", line 7, in <module>
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\extension\application.py", line 616, in launch_instance
    serverapp = cls.initialize_server(argv=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\extension\application.py", line 586, in initialize_server
    serverapp.initialize(
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\config\application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\serverapp.py", line 2757, in initialize
    self.init_webapp()
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\serverapp.py", line 2237, in init_webapp
    self.web_app = ServerWebApplication(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\serverapp.py", line 276, in __init__
    settings = self.init_settings(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\serverapp.py", line 432, in init_settings
    "allow_remote_access": jupyter_app.allow_remote_access,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\traitlets.py", line 687, in __get__
    return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\traitlets.py", line 635, in get
    default = obj.trait_defaults(self.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\traitlets.py", line 1897, in trait_defaults
    return t.cast(Sentinel, self._get_trait_default_generator(names[0])(self))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\traitlets.py", line 1241, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_server\serverapp.py", line 1370, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
Failed to start Amphi: Command '['C:\\Users\\saubert\\AppData\\Local\\Programs\\Python\\Python312\\python.exe', '-m', 'jupyter', 'lab', '--notebook-dir=.', '--port=8888', '--ip=localhost, --ContentManager.allow_hidden=true']' returned non-zero exit status 1.`

OS windows 10

**Comment by tgourdel** [comment]
Thanks Simon, I wonder how I could have let an error like this go through because I had tested it but missed it. I fixed it and released a new version. Sorry for the issue!
Updating it to 0.5.4 should work now!
